export interface RegionPreset {
  code: string
  name: string
  lang: string
  timezone: string
}

export const REGION_PRESETS: RegionPreset[] = [
  { code: 'CN', name: '中国', lang: 'zh-CN', timezone: 'Asia/Shanghai' },
  { code: 'US', name: '美国', lang: 'en-US', timezone: 'America/New_York' },
  { code: 'JP', name: '日本', lang: 'ja-JP', timezone: 'Asia/Tokyo' },
  { code: 'AU', name: '澳大利亚', lang: 'en-AU', timezone: 'Australia/Sydney' },
  { code: 'SG', name: '新加坡', lang: 'en-SG', timezone: 'Asia/Singapore' },
  { code: 'GB', name: '英国', lang: 'en-GB', timezone: 'Europe/London' },
  { code: 'CA', name: '加拿大', lang: 'en-CA', timezone: 'America/Toronto' },
  { code: 'KR', name: '韩国', lang: 'ko-KR', timezone: 'Asia/Seoul' },
  { code: 'DE', name: '德国', lang: 'de-DE', timezone: 'Europe/Berlin' },
  { code: 'FR', name: '法国', lang: 'fr-FR', timezone: 'Europe/Paris' },
  { code: 'IT', name: '意大利', lang: 'it-IT', timezone: 'Europe/Rome' },
  { code: 'ES', name: '西班牙', lang: 'es-ES', timezone: 'Europe/Madrid' },
  { code: 'NL', name: '荷兰', lang: 'nl-NL', timezone: 'Europe/Amsterdam' },
  { code: 'SE', name: '瑞典', lang: 'sv-SE', timezone: 'Europe/Stockholm' },
  { code: 'NO', name: '挪威', lang: 'nb-NO', timezone: 'Europe/Oslo' },
  { code: 'DK', name: '丹麦', lang: 'da-DK', timezone: 'Europe/Copenhagen' },
  { code: 'FI', name: '芬兰', lang: 'fi-FI', timezone: 'Europe/Helsinki' },
  { code: 'RU', name: '俄罗斯', lang: 'ru-RU', timezone: 'Europe/Moscow' },
  { code: 'IN', name: '印度', lang: 'hi-IN', timezone: 'Asia/Kolkata' },
  { code: 'ID', name: '印度尼西亚', lang: 'id-ID', timezone: 'Asia/Jakarta' },
  { code: 'MY', name: '马来西亚', lang: 'ms-MY', timezone: 'Asia/Kuala_Lumpur' },
  { code: 'TH', name: '泰国', lang: 'th-TH', timezone: 'Asia/Bangkok' },
  { code: 'VN', name: '越南', lang: 'vi-VN', timezone: 'Asia/Ho_Chi_Minh' },
  { code: 'PH', name: '菲律宾', lang: 'en-PH', timezone: 'Asia/Manila' },
  { code: 'NZ', name: '新西兰', lang: 'en-NZ', timezone: 'Pacific/Auckland' },
  { code: 'BR', name: '巴西', lang: 'pt-BR', timezone: 'America/Sao_Paulo' },
  { code: 'MX', name: '墨西哥', lang: 'es-MX', timezone: 'America/Mexico_City' },
  { code: 'AR', name: '阿根廷', lang: 'es-AR', timezone: 'America/Argentina/Buenos_Aires' },
  { code: 'CL', name: '智利', lang: 'es-CL', timezone: 'America/Santiago' },
  { code: 'CO', name: '哥伦比亚', lang: 'es-CO', timezone: 'America/Bogota' },
  { code: 'PE', name: '秘鲁', lang: 'es-PE', timezone: 'America/Lima' },
  { code: 'ZA', name: '南非', lang: 'en-ZA', timezone: 'Africa/Johannesburg' },
  { code: 'EG', name: '埃及', lang: 'ar-EG', timezone: 'Africa/Cairo' },
  { code: 'AE', name: '阿联酋', lang: 'ar-AE', timezone: 'Asia/Dubai' },
  { code: 'SA', name: '沙特阿拉伯', lang: 'ar-SA', timezone: 'Asia/Riyadh' },
  { code: 'TR', name: '土耳其', lang: 'tr-TR', timezone: 'Europe/Istanbul' },
  { code: 'IL', name: '以色列', lang: 'he-IL', timezone: 'Asia/Jerusalem' },
  { code: 'HK', name: '中国香港', lang: 'zh-HK', timezone: 'Asia/Hong_Kong' },
  { code: 'MO', name: '中国澳门', lang: 'zh-MO', timezone: 'Asia/Macau' },
  { code: 'TW', name: '中国台湾', lang: 'zh-TW', timezone: 'Asia/Taipei' },
  { code: 'AF', name: '阿富汗', lang: 'fa-AF', timezone: 'Asia/Kabul' },
  { code: 'AL', name: '阿尔巴尼亚', lang: 'sq-AL', timezone: 'Europe/Tirane' },
  { code: 'DZ', name: '阿尔及利亚', lang: 'ar-DZ', timezone: 'Africa/Algiers' },
  { code: 'AD', name: '安道尔', lang: 'ca-AD', timezone: 'Europe/Andorra' },
  { code: 'AO', name: '安哥拉', lang: 'pt-AO', timezone: 'Africa/Luanda' },
  { code: 'AG', name: '安提瓜和巴布达', lang: 'en-AG', timezone: 'America/Antigua' },
  { code: 'AM', name: '亚美尼亚', lang: 'hy-AM', timezone: 'Asia/Yerevan' },
  { code: 'AT', name: '奥地利', lang: 'de-AT', timezone: 'Europe/Vienna' },
  { code: 'AZ', name: '阿塞拜疆', lang: 'az-AZ', timezone: 'Asia/Baku' },
  { code: 'BS', name: '巴哈马', lang: 'en-BS', timezone: 'America/Nassau' },
  { code: 'BH', name: '巴林', lang: 'ar-BH', timezone: 'Asia/Bahrain' },
  { code: 'BD', name: '孟加拉国', lang: 'bn-BD', timezone: 'Asia/Dhaka' },
  { code: 'BB', name: '巴巴多斯', lang: 'en-BB', timezone: 'America/Barbados' },
  { code: 'BY', name: '白俄罗斯', lang: 'be-BY', timezone: 'Europe/Minsk' },
  { code: 'BE', name: '比利时', lang: 'nl-BE', timezone: 'Europe/Brussels' },
  { code: 'BZ', name: '伯利兹', lang: 'en-BZ', timezone: 'America/Belize' },
  { code: 'BJ', name: '贝宁', lang: 'fr-BJ', timezone: 'Africa/Porto-Novo' },
  { code: 'BT', name: '不丹', lang: 'dz-BT', timezone: 'Asia/Thimphu' },
  { code: 'BO', name: '玻利维亚', lang: 'es-BO', timezone: 'America/La_Paz' },
  { code: 'BA', name: '波黑', lang: 'bs-BA', timezone: 'Europe/Sarajevo' },
  { code: 'BW', name: '博茨瓦纳', lang: 'en-BW', timezone: 'Africa/Gaborone' },
  { code: 'BN', name: '文莱', lang: 'ms-BN', timezone: 'Asia/Brunei' },
  { code: 'BG', name: '保加利亚', lang: 'bg-BG', timezone: 'Europe/Sofia' },
  { code: 'BF', name: '布基纳法索', lang: 'fr-BF', timezone: 'Africa/Ouagadougou' },
  { code: 'BI', name: '布隆迪', lang: 'fr-BI', timezone: 'Africa/Bujumbura' },
  { code: 'KH', name: '柬埔寨', lang: 'km-KH', timezone: 'Asia/Phnom_Penh' },
  { code: 'CM', name: '喀麦隆', lang: 'fr-CM', timezone: 'Africa/Douala' },
  { code: 'CV', name: '佛得角', lang: 'pt-CV', timezone: 'Atlantic/Cape_Verde' },
  { code: 'CF', name: '中非', lang: 'fr-CF', timezone: 'Africa/Bangui' },
  { code: 'TD', name: '乍得', lang: 'fr-TD', timezone: 'Africa/Ndjamena' },
  { code: 'KM', name: '科摩罗', lang: 'ar-KM', timezone: 'Indian/Comoro' },
  { code: 'CG', name: '刚果共和国', lang: 'fr-CG', timezone: 'Africa/Brazzaville' },
  { code: 'CD', name: '刚果（金）', lang: 'fr-CD', timezone: 'Africa/Kinshasa' },
  { code: 'CR', name: '哥斯达黎加', lang: 'es-CR', timezone: 'America/Costa_Rica' },
  { code: 'CI', name: '科特迪瓦', lang: 'fr-CI', timezone: 'Africa/Abidjan' },
  { code: 'HR', name: '克罗地亚', lang: 'hr-HR', timezone: 'Europe/Zagreb' },
  { code: 'CU', name: '古巴', lang: 'es-CU', timezone: 'America/Havana' },
  { code: 'CY', name: '塞浦路斯', lang: 'el-CY', timezone: 'Asia/Nicosia' },
  { code: 'CZ', name: '捷克', lang: 'cs-CZ', timezone: 'Europe/Prague' },
  { code: 'DJ', name: '吉布提', lang: 'fr-DJ', timezone: 'Africa/Djibouti' },
  { code: 'DM', name: '多米尼克', lang: 'en-DM', timezone: 'America/Dominica' },
  { code: 'DO', name: '多米尼加', lang: 'es-DO', timezone: 'America/Santo_Domingo' },
  { code: 'EC', name: '厄瓜多尔', lang: 'es-EC', timezone: 'America/Guayaquil' },
  { code: 'SV', name: '萨尔瓦多', lang: 'es-SV', timezone: 'America/El_Salvador' },
  { code: 'GQ', name: '赤道几内亚', lang: 'es-GQ', timezone: 'Africa/Malabo' },
  { code: 'ER', name: '厄立特里亚', lang: 'ti-ER', timezone: 'Africa/Asmara' },
  { code: 'EE', name: '爱沙尼亚', lang: 'et-EE', timezone: 'Europe/Tallinn' },
  { code: 'SZ', name: '斯威士兰', lang: 'en-SZ', timezone: 'Africa/Mbabane' },
  { code: 'ET', name: '埃塞俄比亚', lang: 'am-ET', timezone: 'Africa/Addis_Ababa' },
  { code: 'FJ', name: '斐济', lang: 'en-FJ', timezone: 'Pacific/Fiji' },
  { code: 'GA', name: '加蓬', lang: 'fr-GA', timezone: 'Africa/Libreville' },
  { code: 'GM', name: '冈比亚', lang: 'en-GM', timezone: 'Africa/Banjul' },
  { code: 'GE', name: '格鲁吉亚', lang: 'ka-GE', timezone: 'Asia/Tbilisi' },
  { code: 'GH', name: '加纳', lang: 'en-GH', timezone: 'Africa/Accra' },
  { code: 'GR', name: '希腊', lang: 'el-GR', timezone: 'Europe/Athens' },
  { code: 'GD', name: '格林纳达', lang: 'en-GD', timezone: 'America/Grenada' },
  { code: 'GT', name: '危地马拉', lang: 'es-GT', timezone: 'America/Guatemala' },
  { code: 'GN', name: '几内亚', lang: 'fr-GN', timezone: 'Africa/Conakry' },
  { code: 'GW', name: '几内亚比绍', lang: 'pt-GW', timezone: 'Africa/Bissau' },
  { code: 'GY', name: '圭亚那', lang: 'en-GY', timezone: 'America/Guyana' },
  { code: 'HT', name: '海地', lang: 'fr-HT', timezone: 'America/Port-au-Prince' },
  { code: 'HN', name: '洪都拉斯', lang: 'es-HN', timezone: 'America/Tegucigalpa' },
  { code: 'HU', name: '匈牙利', lang: 'hu-HU', timezone: 'Europe/Budapest' },
  { code: 'IS', name: '冰岛', lang: 'is-IS', timezone: 'Atlantic/Reykjavik' },
  { code: 'IR', name: '伊朗', lang: 'fa-IR', timezone: 'Asia/Tehran' },
  { code: 'IQ', name: '伊拉克', lang: 'ar-IQ', timezone: 'Asia/Baghdad' },
  { code: 'IE', name: '爱尔兰', lang: 'en-IE', timezone: 'Europe/Dublin' },
  { code: 'JM', name: '牙买加', lang: 'en-JM', timezone: 'America/Jamaica' },
  { code: 'JO', name: '约旦', lang: 'ar-JO', timezone: 'Asia/Amman' },
  { code: 'KZ', name: '哈萨克斯坦', lang: 'kk-KZ', timezone: 'Asia/Almaty' },
  { code: 'KE', name: '肯尼亚', lang: 'en-KE', timezone: 'Africa/Nairobi' },
  { code: 'KI', name: '基里巴斯', lang: 'en-KI', timezone: 'Pacific/Tarawa' },
  { code: 'KW', name: '科威特', lang: 'ar-KW', timezone: 'Asia/Kuwait' },
  { code: 'KG', name: '吉尔吉斯斯坦', lang: 'ky-KG', timezone: 'Asia/Bishkek' },
  { code: 'LA', name: '老挝', lang: 'lo-LA', timezone: 'Asia/Vientiane' },
  { code: 'LV', name: '拉脱维亚', lang: 'lv-LV', timezone: 'Europe/Riga' },
  { code: 'LB', name: '黎巴嫩', lang: 'ar-LB', timezone: 'Asia/Beirut' },
  { code: 'LS', name: '莱索托', lang: 'en-LS', timezone: 'Africa/Maseru' },
  { code: 'LR', name: '利比里亚', lang: 'en-LR', timezone: 'Africa/Monrovia' },
  { code: 'LY', name: '利比亚', lang: 'ar-LY', timezone: 'Africa/Tripoli' },
  { code: 'LI', name: '列支敦士登', lang: 'de-LI', timezone: 'Europe/Vaduz' },
  { code: 'LT', name: '立陶宛', lang: 'lt-LT', timezone: 'Europe/Vilnius' },
  { code: 'LU', name: '卢森堡', lang: 'fr-LU', timezone: 'Europe/Luxembourg' },
  { code: 'MG', name: '马达加斯加', lang: 'fr-MG', timezone: 'Indian/Antananarivo' },
  { code: 'MW', name: '马拉维', lang: 'en-MW', timezone: 'Africa/Blantyre' },
  { code: 'MV', name: '马尔代夫', lang: 'dv-MV', timezone: 'Indian/Maldives' },
  { code: 'ML', name: '马里', lang: 'fr-ML', timezone: 'Africa/Bamako' },
  { code: 'MT', name: '马耳他', lang: 'mt-MT', timezone: 'Europe/Malta' },
  { code: 'MH', name: '马绍尔群岛', lang: 'en-MH', timezone: 'Pacific/Majuro' },
  { code: 'MR', name: '毛里塔尼亚', lang: 'ar-MR', timezone: 'Africa/Nouakchott' },
  { code: 'MU', name: '毛里求斯', lang: 'en-MU', timezone: 'Indian/Mauritius' },
  { code: 'FM', name: '密克罗尼西亚', lang: 'en-FM', timezone: 'Pacific/Pohnpei' },
  { code: 'MD', name: '摩尔多瓦', lang: 'ro-MD', timezone: 'Europe/Chisinau' },
  { code: 'MC', name: '摩纳哥', lang: 'fr-MC', timezone: 'Europe/Monaco' },
  { code: 'MN', name: '蒙古', lang: 'mn-MN', timezone: 'Asia/Ulaanbaatar' },
  { code: 'ME', name: '黑山', lang: 'sr-ME', timezone: 'Europe/Podgorica' },
  { code: 'MA', name: '摩洛哥', lang: 'ar-MA', timezone: 'Africa/Casablanca' },
  { code: 'MZ', name: '莫桑比克', lang: 'pt-MZ', timezone: 'Africa/Maputo' },
  { code: 'MM', name: '缅甸', lang: 'my-MM', timezone: 'Asia/Yangon' },
  { code: 'NA', name: '纳米比亚', lang: 'en-NA', timezone: 'Africa/Windhoek' },
  { code: 'NR', name: '瑙鲁', lang: 'en-NR', timezone: 'Pacific/Nauru' },
  { code: 'NP', name: '尼泊尔', lang: 'ne-NP', timezone: 'Asia/Kathmandu' },
  { code: 'NI', name: '尼加拉瓜', lang: 'es-NI', timezone: 'America/Managua' },
  { code: 'NE', name: '尼日尔', lang: 'fr-NE', timezone: 'Africa/Niamey' },
  { code: 'NG', name: '尼日利亚', lang: 'en-NG', timezone: 'Africa/Lagos' },
  { code: 'MK', name: '北马其顿', lang: 'mk-MK', timezone: 'Europe/Skopje' },
  { code: 'OM', name: '阿曼', lang: 'ar-OM', timezone: 'Asia/Muscat' },
  { code: 'PK', name: '巴基斯坦', lang: 'ur-PK', timezone: 'Asia/Karachi' },
  { code: 'PW', name: '帕劳', lang: 'en-PW', timezone: 'Pacific/Palau' },
  { code: 'PA', name: '巴拿马', lang: 'es-PA', timezone: 'America/Panama' },
  { code: 'PG', name: '巴布亚新几内亚', lang: 'en-PG', timezone: 'Pacific/Port_Moresby' },
  { code: 'PY', name: '巴拉圭', lang: 'es-PY', timezone: 'America/Asuncion' },
  { code: 'PL', name: '波兰', lang: 'pl-PL', timezone: 'Europe/Warsaw' },
  { code: 'PT', name: '葡萄牙', lang: 'pt-PT', timezone: 'Europe/Lisbon' },
  { code: 'QA', name: '卡塔尔', lang: 'ar-QA', timezone: 'Asia/Qatar' },
  { code: 'RO', name: '罗马尼亚', lang: 'ro-RO', timezone: 'Europe/Bucharest' },
  { code: 'RW', name: '卢旺达', lang: 'rw-RW', timezone: 'Africa/Kigali' },
  { code: 'KN', name: '圣基茨和尼维斯', lang: 'en-KN', timezone: 'America/St_Kitts' },
  { code: 'LC', name: '圣卢西亚', lang: 'en-LC', timezone: 'America/St_Lucia' },
  { code: 'VC', name: '圣文森特和格林纳丁斯', lang: 'en-VC', timezone: 'America/St_Vincent' },
  { code: 'WS', name: '萨摩亚', lang: 'en-WS', timezone: 'Pacific/Apia' },
  { code: 'SM', name: '圣马力诺', lang: 'it-SM', timezone: 'Europe/San_Marino' },
  { code: 'ST', name: '圣多美和普林西比', lang: 'pt-ST', timezone: 'Africa/Sao_Tome' },
  { code: 'SN', name: '塞内加尔', lang: 'fr-SN', timezone: 'Africa/Dakar' },
  { code: 'RS', name: '塞尔维亚', lang: 'sr-RS', timezone: 'Europe/Belgrade' },
  { code: 'SC', name: '塞舌尔', lang: 'en-SC', timezone: 'Indian/Mahe' },
  { code: 'SL', name: '塞拉利昂', lang: 'en-SL', timezone: 'Africa/Freetown' },
  { code: 'SK', name: '斯洛伐克', lang: 'sk-SK', timezone: 'Europe/Bratislava' },
  { code: 'SI', name: '斯洛文尼亚', lang: 'sl-SI', timezone: 'Europe/Ljubljana' },
  { code: 'SB', name: '所罗门群岛', lang: 'en-SB', timezone: 'Pacific/Guadalcanal' },
  { code: 'SO', name: '索马里', lang: 'so-SO', timezone: 'Africa/Mogadishu' },
  { code: 'SS', name: '南苏丹', lang: 'en-SS', timezone: 'Africa/Juba' },
  { code: 'LK', name: '斯里兰卡', lang: 'si-LK', timezone: 'Asia/Colombo' },
  { code: 'SD', name: '苏丹', lang: 'ar-SD', timezone: 'Africa/Khartoum' },
  { code: 'SR', name: '苏里南', lang: 'nl-SR', timezone: 'America/Paramaribo' },
  { code: 'CH', name: '瑞士', lang: 'de-CH', timezone: 'Europe/Zurich' },
  { code: 'SY', name: '叙利亚', lang: 'ar-SY', timezone: 'Asia/Damascus' },
  { code: 'TJ', name: '塔吉克斯坦', lang: 'tg-TJ', timezone: 'Asia/Dushanbe' },
  { code: 'TZ', name: '坦桑尼亚', lang: 'sw-TZ', timezone: 'Africa/Dar_es_Salaam' },
  { code: 'TL', name: '东帝汶', lang: 'pt-TL', timezone: 'Asia/Dili' },
  { code: 'TG', name: '多哥', lang: 'fr-TG', timezone: 'Africa/Lome' },
  { code: 'TO', name: '汤加', lang: 'en-TO', timezone: 'Pacific/Tongatapu' },
  { code: 'TT', name: '特立尼达和多巴哥', lang: 'en-TT', timezone: 'America/Port_of_Spain' },
  { code: 'TN', name: '突尼斯', lang: 'ar-TN', timezone: 'Africa/Tunis' },
  { code: 'TM', name: '土库曼斯坦', lang: 'tk-TM', timezone: 'Asia/Ashgabat' },
  { code: 'TV', name: '图瓦卢', lang: 'en-TV', timezone: 'Pacific/Funafuti' },
  { code: 'UG', name: '乌干达', lang: 'en-UG', timezone: 'Africa/Kampala' },
  { code: 'UA', name: '乌克兰', lang: 'uk-UA', timezone: 'Europe/Kyiv' },
  { code: 'UY', name: '乌拉圭', lang: 'es-UY', timezone: 'America/Montevideo' },
  { code: 'UZ', name: '乌兹别克斯坦', lang: 'uz-UZ', timezone: 'Asia/Tashkent' },
  { code: 'VU', name: '瓦努阿图', lang: 'en-VU', timezone: 'Pacific/Efate' },
  { code: 'VA', name: '梵蒂冈', lang: 'it-VA', timezone: 'Europe/Vatican' },
  { code: 'VE', name: '委内瑞拉', lang: 'es-VE', timezone: 'America/Caracas' },
  { code: 'YE', name: '也门', lang: 'ar-YE', timezone: 'Asia/Aden' },
  { code: 'ZM', name: '赞比亚', lang: 'en-ZM', timezone: 'Africa/Lusaka' },
  { code: 'ZW', name: '津巴布韦', lang: 'en-ZW', timezone: 'Africa/Harare' },
]

export const REGION_OPTIONS = [
  { value: '', label: '自动/手动设置语言和时区' },
  ...REGION_PRESETS.map(item => ({
    value: item.code,
    label: `${item.name} (${item.lang}, ${item.timezone})`,
  })),
]

export function findRegionPreset(code: string) {
  return REGION_PRESETS.find(item => item.code === code)
}

export function findRegionPresetByLocale(lang?: string, timezone?: string) {
  if (!lang || !timezone) return undefined
  return REGION_PRESETS.find(item => item.lang === lang && item.timezone === timezone)
}
